apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: webhook
  namespace: eo-workflow
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: debug-events
  namespace: eo-workflow
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cog-transformer
  namespace: eo-workflow
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: completion-tracker
  namespace: eo-workflow
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fmask
  namespace: eo-workflow
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: error-handler
  namespace: eo-workflow
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
