apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: eo-workflow
  labels:
    app.kubernetes.io/name: redis-data
    app.kubernetes.io/part-of: eo-processing-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-cinder-sc-delete
