apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: eo-event-broker
  namespace: eo-workflow
  annotations:
    eventing.knative.dev/broker.class: MTChannelBasedBroker
  labels:
    app.kubernetes.io/name: eo-event-broker
    app.kubernetes.io/part-of: eo-processing-system
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: config-br-default-channel
    namespace: knative-eventing
  delivery:
    retry: 10
    backoffPolicy: exponential
    backoffDelay: PT0.2S
