apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: eo-event-broker
  namespace: eo-workflow
  annotations:
    eventing.knative.dev/broker.class: MTBroker
  labels:
    app.kubernetes.io/name: eo-event-broker
    app.kubernetes.io/part-of: eo-processing-system
spec: {}
