apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: eo-event-broker
  namespace: eo-workflow
  labels:
    app.kubernetes.io/name: eo-event-broker
    app.kubernetes.io/part-of: eo-processing-system
  # annotations:  eventing.knative.dev/broker.class: MTChannelBasedBroker
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: config-br-default-channel
    namespace: knative-eventing
