apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: search-trigger
  namespace: eo-workflow
spec:
  broker: eo-event-broker
  filter:
    attributes:
      type: eo.search.requested
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: search
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: asset-scheduler-trigger
  namespace: eo-workflow
spec:
  broker: eo-event-broker
  filter:
    attributes:
      type: eo.scene.assets.registered
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: asset-scheduler
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: asset-processor-trigger
  namespace: eo-workflow
spec:
  broker: eo-event-broker
  filter:
    attributes:
      type: eo.asset.process
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: asset-processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: scene-discovery-trigger
  namespace: eo-workflow
spec:
  broker: eo-event-broker
  filter:
    attributes:
      type: eo.scene.discovered
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: asset-processor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: cog-transformer-trigger
  namespace: eo-workflow
spec:
  broker: eo-event-broker
  filter:
    attributes:
      type: eo.asset.ingested
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: cog-transformer
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: completion-tracker-register-trigger
  namespace: eo-workflow
spec:
  broker: eo-event-broker
  filter:
    attributes:
      type: eo.scene.assets.registered
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: completion-tracker
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: completion-tracker-asset-trigger
  namespace: eo-workflow
spec:
  broker: eo-event-broker
  filter:
    attributes:
      type: eo.asset.transformed
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: completion-tracker
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: fmask-trigger
  namespace: eo-workflow
spec:
  broker: eo-event-broker
  filter:
    attributes:
      type: eo.scene.ready
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: fmask
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: fmask-cog-trigger
  namespace: eo-workflow
spec:
  broker: eo-event-broker
  filter:
    attributes:
      type: eo.fmask.completed
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: cog-transformer
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: error-handler-trigger
  namespace: eo-workflow
spec:
  broker: eo-event-broker
  filter:
    attributes:
      type: eo.processing.error
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: error-handler
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: debug-all-events-trigger
  namespace: eo-workflow
spec:
  broker: eo-event-broker
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: debug-events
