apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: webhook-sink
  namespace: eo-workflow
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: webhook
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: eo-event-broker
