apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-monitor
  namespace: eo-workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-monitor
  template:
    metadata:
      labels:
        app: event-monitor
    spec:
      containers:
      - name: event-display
        image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display
---
apiVersion: v1
kind: Service
metadata:
  name: event-monitor
  namespace: eo-workflow
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: event-monitor
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: monitor-all-events
  namespace: eo-workflow
spec:
  broker: eo-event-broker
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: event-monitor
