apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: test-ping
  namespace: eo-workflow
spec:
  schedule: "*/1 * * * *" # every minute
  data: '{"message": "Test event for EO workflow"}'
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: eo-event-broker
