apiVersion: sources.knative.dev/v1
kind: ContainerSource
metadata:
  name: ingestion-source
  namespace: eo-workflow
  labels:
    app.kubernetes.io/name: ingestion-source
    app.kubernetes.io/part-of: eo-processing-system
spec:
  template:
    spec:
      containers:
      - image: docker.io/davidandw190/eo-ingestion:latest
        name: ingestion-source
        env:
        - name: MINIO_ENDPOINT
          value: "minio.eo-workflow.svc.cluster.local:9000"
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_KEY
          value: "minioadmin"
        - name: RAW_BUCKET
          value: "raw-assets"
        - name: STAC_COLLECTION
          value: "sentinel-2-l2a"
        - name: EVENT_SOURCE
          value: "eo-workflow/ingestion"
        - name: MAX_RETRIES
          value: "3"
        - name: MAX_ITEMS
          value: "1"
        - name: CONNECTION_TIMEOUT
          value: "5"
        - name: MAX_WORKERS
          value: "4"
        - name: REDIS_HOST
          value: "redis.eo-workflow.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_KEY_PREFIX
          value: "eo:ingestion:"
        - name: REDIS_KEY_EXPIRY
          value: "86400"
        resources:
          limits:
            cpu: 2
            memory: 8Gi
          requests:
            cpu: 500m
            memory: 2Gi
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: eo-event-broker
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  namespace: eo-workflow
  labels:
    app.kubernetes.io/name: ingestion-service
    app.kubernetes.io/part-of: eo-processing-system
spec:
  selector:
    sources.knative.dev/containerSource: ingestion-source
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
